# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Python_Projects\PyQt5 Progress Bar\mmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from components.msgboxpy import *
import socket
import sys


class Ui_Main_Menu(object):
    def setupUi(self, Main_Menu):
        if socket.gethostbyname(socket.gethostname()) == "127.0.0.1":
            alert("No internet Connection This Program needs an active internet connection",Styles.Icons.ICON_ERROR,"IEx12076")
        else:
            from components.actions import Main 
            import components.actions as acts
            actions = Main.MMenu
            Main_Menu.setObjectName("Main_Menu")
            Main_Menu.resize(807, 446)
            self.centralwidget = QtWidgets.QWidget(Main_Menu)
            self.centralwidget.setObjectName("centralwidget")
            self.title = QtWidgets.QLabel(self.centralwidget)
            self.title.setGeometry(QtCore.QRect(10, 0, 781, 101))
            self.title.setObjectName("title")
            self.ao_groupbox = QtWidgets.QGroupBox(self.centralwidget)
            self.ao_groupbox.setGeometry(QtCore.QRect(10, 130, 351, 201))
            self.ao_groupbox.setObjectName("ao_groupbox")
            self.wa_btn = QtWidgets.QPushButton(self.ao_groupbox,clicked = lambda:actions.open_watsintro(Main.MMenu,Main_Menu))
            self.wa_btn.setGeometry(QtCore.QRect(57, 40, 231, 41))
            self.wa_btn.setObjectName("wa_btn")
            self.other_groupbox = QtWidgets.QGroupBox(self.centralwidget)
            self.other_groupbox.setGeometry(QtCore.QRect(440, 130, 351, 201))
            self.other_groupbox.setObjectName("other_groupbox")
            self.img_to_text_btn = QtWidgets.QPushButton(self.other_groupbox,clicked = lambda:actions.open_image_to_text())
            self.img_to_text_btn.setGeometry(QtCore.QRect(28, 30, 141, 41))
            self.img_to_text_btn.setObjectName("img_to_text_btn")
            self.text_to_hw_btn = QtWidgets.QPushButton(self.other_groupbox,clicked = lambda:actions.open_text_to_image())
            self.text_to_hw_btn.setGeometry(QtCore.QRect(190, 30, 141, 41))
            self.text_to_hw_btn.setObjectName("text_to_hw_btn")
            Main_Menu.setCentralWidget(self.centralwidget)
            self.menubar = QtWidgets.QMenuBar(Main_Menu)
            self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
            self.menubar.setObjectName("menubar")
            Main_Menu.setMenuBar(self.menubar)
            self.statusbar = QtWidgets.QStatusBar(Main_Menu)
            self.statusbar.setObjectName("statusbar")
            Main_Menu.setStatusBar(self.statusbar)

            self.retranslateUi(Main_Menu)
            QtCore.QMetaObject.connectSlotsByName(Main_Menu)

    def retranslateUi(self, Main_Menu):
        _translate = QtCore.QCoreApplication.translate
        Main_Menu.setWindowTitle(_translate("Main_Menu", "Main Menu"))
        self.title.setText(_translate("Main_Menu", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">W&amp;G Automator</span></p><p align=\"center\"><span style=\" font-size:16pt; font-style:italic;\">By AbdulWahab</span></p></body></html>"))
        self.ao_groupbox.setTitle(_translate("Main_Menu", "                                       Automation Options"))
        self.wa_btn.setText(_translate("Main_Menu", "Whatsapp Automation"))
        self.other_groupbox.setTitle(_translate("Main_Menu", "                                              Other Options"))
        self.img_to_text_btn.setText(_translate("Main_Menu", "Image to Text art"))
        self.text_to_hw_btn.setText(_translate("Main_Menu", "Text to Hand Writing"))


if __name__ == "__main__":
    if socket.gethostbyname(socket.gethostname()) == "127.0.0.1":
        alert("No internet Connection This Program needs an active internet connection",Styles.Icons.ICON_ERROR,"IEx12076")
    else:
        import components.actions as acts
        app = QtWidgets.QApplication(sys.argv)
        Main_Menu = QtWidgets.QMainWindow()
        ui = Ui_Main_Menu()
        acts.window = Main_Menu
        ui.setupUi(Main_Menu)
        Main_Menu.show()
        sys.exit(app.exec_())
