# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Python_Projects\PyQt5 Progress Bar\mgw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import timecv
import pywhatkit
from msgboxpy import *
from pywhatkit import exceptions

def startAWM(group_invite_link="",message="",time="1:00",cmbBox=None,option_act=None):
    import cv
    group_invite_link = cv.get_id_from_invite_link(group_invite_link)
    
    rtime = timecv.convertTo24(f"{time.strip()} {cmbBox.currentText()}")
    hour = rtime.split(":")[0]
    minute = rtime.split(":")[1]

    try:
        if option_act.isChecked():
            pywhatkit.sendwhatmsg_to_group(group_invite_link,message,int(hour),int(minute),4,tab_close=True)
        else:
            pywhatkit.sendwhatmsg_to_group(group_invite_link,message,int(hour),int(minute),4)  
    except exceptions.InternetException:
        al = alert(f"AWM - Auto Whatsapp Messager requires an active network Connection!",Styles.Icons.ICON_ERROR|Styles.Buttons.RETRY_CANCEL,"Internet Error")
        if al == "retry":
            print(socket.gethostbyname(socket.gethostname()))
            import socket
            if socket.gethostbyname(socket.gethostname()) == "121.1.1.0":pass        
    except exceptions.CountryCodeException:
        alert(f"Country code missing from Number: {group_invite_link}",Styles.Icons.ICON_ERROR|Styles.Buttons.OK,"Country Code Error")         
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 0, 561, 71))
        self.label.setObjectName("label")
        self.quickWidget = QtQuickWidgets.QQuickWidget(self.centralwidget)
        self.quickWidget.setGeometry(QtCore.QRect(-200, 640, 300, 200))
        self.quickWidget.setResizeMode(QtQuickWidgets.QQuickWidget.SizeRootObjectToView)
        self.quickWidget.setObjectName("quickWidget")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 120, 151, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 81, 31))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(100, 220, 151, 181))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 120, 81, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 120, 241, 291))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=
        lambda: startAWM(
        group_invite_link=self.lineEdit_2.text(),
        message=self.plainTextEdit.toPlainText(),
        time=self.lineEdit_3.text(),
        cmbBox=self.comboBox,
        option_act = self.checkBox))
        
        self.pushButton.setGeometry(QtCore.QRect(60, 420, 231, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 101, 31))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 91, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 170, 151, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AWM - Auto Whatsapp Messager (Group Messager)"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">AWM - Group Messager</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Time:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "AM"))
        self.comboBox.setItemText(1, _translate("MainWindow", "PM"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.checkBox.setText(_translate("MainWindow", "Automatically Close Tabs"))
        self.pushButton.setText(_translate("MainWindow", "Start Auto Messager"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Invite Link:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Message: </span></p></body></html>"))
from PyQt5 import QtQuickWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
