# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Python_Projects\PyQt5 Progress Bar\mw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from msgboxpy import alert,Styles
import timecv
import pywhatkit
import datetime
from pywhatkit import exceptions
import os

def back(mw):
    mw.destroy()
    os.system("python components/wmenu.py")

def startAWM(number="51",message="",time="1:00",cmbBox=None,option_act=None):
    rtime = timecv.convertTo24(f"{time.strip()} {cmbBox.currentText()}")
    hour = rtime.split(":")[0]
    minute = rtime.split(":")[1]
 
    try:
        if option_act.isChecked():
            pywhatkit.sendwhatmsg(number,message,int(hour),int(minute),4,tab_close=True)
        else:
            pywhatkit.sendwhatmsg(number,message,int(hour),int(minute),4)  
    except exceptions.InternetException:
        al = alert(f"AWM - Auto Whatsapp Messager requires an active network Connection!",Styles.Icons.ICON_ERROR|Styles.Buttons.RETRY_CANCEL,"Internet Error")
        if al == "retry":
            import socket
            if socket.gethostbyname(socket.gethostname()) == "121.1.1.0":pass        
    except exceptions.CountryCodeException:
        alert(f"Country code missing from Number: {number}",Styles.Icons.ICON_ERROR|Styles.Buttons.OK,"Country Code Error")         
    
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 561, 71))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 140, 241, 291))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.checkBox.setObjectName("checkBox")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 81, 31))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        
        self.plainTextEdit.setGeometry(QtCore.QRect(100, 240, 151, 181))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 91, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 190, 151, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setValidator(QtGui.QIntValidator(self.centralwidget))
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 81, 31))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 140, 81, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
    
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 140, 151, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: startAWM(number=self.lineEdit_2.text(),message=self.plainTextEdit.toPlainText(),time=self.lineEdit_3.text(),cmbBox=self.comboBox,option_act = self.checkBox))
        
        self.pushButton.setGeometry(QtCore.QRect(60, 440, 231, 41))
        self.pushButton.setObjectName("pushButton")
        
        self.back = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: back(MainWindow))
        
        self.back.setGeometry(QtCore.QRect(60, 540, 231, 41))
        self.back.setObjectName("back")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
                                         
                        
    def retranslateUi(self, MainWindow):
        hour = datetime.datetime.now().strftime("%H")
        minute = datetime.datetime.now().strftime("%M")
        p_or_a = datetime.datetime.now().strftime("%p")
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AWM - Auto Whatsapp Messager"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">AWM - Contact Messager</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.checkBox.setText(_translate("MainWindow", "Automatically Close Tabs"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Time:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Message: </span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Number:</span></p></body></html>"))
        if p_or_a == "PM":
            self.comboBox.setItemText(0, _translate("MainWindow", "PM"))
            self.comboBox.setItemText(1, _translate("MainWindow", "AM"))
        else:
            self.comboBox.setItemText(0, _translate("MainWindow", "AM"))
            self.comboBox.setItemText(1, _translate("MainWindow", "PM"))                
        self.lineEdit_3.setText(_translate("MainWindow",f"{hour}:{str(int(minute)+2)}"))    
        self.back.setText(_translate("MainWindow", "Back"))   
        self.pushButton.setText(_translate("MainWindow", "Start Auto Messager"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
